[package]
name = "basic_reactive_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
once_cell = "1.18.0"
clearscreen = "2.0.1"
